# baseURL = "http://localhost:1313"
baseURL = "https://blog.ichi.tech"
theme = "tale"
#theme = "ichilog"
# languageCode = "ja"
# defaultContentLanguage = "ja"
title = "ICHILOG"

[Params]
test_params = "TEST PARAMS!"
