name: "HUGO Deploy"

on:
  push:
    branches:
      - actions-test

jobs:
  practice:
    runs-on: ubuntu-20.04
    steps:
      - run: cat /etc/os-release
      - run: docker --version
      - run: docker-compose --version
      - run: docker images
  practice2:
    runs-on: ubuntu-20.04
    container: ubuntu:18.04
    steps:
      - run: cat /etc/os-release
  build-hugo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: bravebright/ichilog
          depth: 1
          submodule: true
          path: ichilog
          token: ${{ secrets.GitHub_PAT }}
      - run: whoami && id
      - run: ls -lah ./ichilog/docs/
      - run: docker-compose run --rm -f ./ichilog/docker-compose.yml builder
      - run: ls -lah ./ichilog/docs/
