name: "HUGO Deploy"

on:
  push:
    branches:
      - actions-test

jobs:
  practice:
    runs-on: ubuntu-20.04
    steps:
      - run: cat /etc/os-release
      - run: docker --version
      - run: docker-compose --version
      - run: docker images
  practice2:
    runs-on: ubuntu-20.04
    container: ubuntu:18.04
    steps:
      - run: cat /etc/os-release
  check:
    runs-on: ubuntu-20.04
    steps:
      - run: whoami
      - run: id
      - run: docker --version
      - run: docker-compose --version
  build-hugo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: bravebright/ichilog
          fetch-depth: 1
          submodules: true
          path: ichilog
          token: ${{ secrets.ACTIONS_PAT }}
      - run: HUGO_UID=$(id -u) HUGO_GID=$(id -g) docker-compose -f ./ichilog/docker-compose.yml run --rm builder
      - run: git status
      - run: git add ./docs
      - run: git commit -m "update docs use commit $(git log -n 1 --format=%H)"
      - run: git log -n 2
